apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/committer: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/contextDir: C:\dev\refarch\refarch-reefer-ml\simulator
    commit.image.appsody.dev/date: Fri May 29 13:02:34 2020 -0500
    commit.image.appsody.dev/message: scoring prediction bypass (#63)
    image.opencontainers.org/created: "2020-06-19T17:04:30+01:00"
    image.opencontainers.org/documentation: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
    image.opencontainers.org/revision: a199280ba8e998618c2a963463d8339379f16062
    image.opencontainers.org/source: |
      https://github.com/ibm-cloud-architecture/refarch-reefer-ml/tree/master
    image.opencontainers.org/url: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.1
    stack.appsody.dev/created: 2019-11-14T10:29:19+0000
    stack.appsody.dev/digest: sha256:1405bd0d18b449f90d98ca31ba7c0a53d40dae6e62362a815cedde63bd2a18d2
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: appsody/python-flask:0.1.6
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: refarch-kc
    image.opencontainers.org/title: reefer-simulator
    stack.appsody.dev/version: 0.1.6
  name: reefer-simulator
spec:
  applicationImage: ibmcase/kcontainer-reefer-simulator-appsody:0.1.51
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: TELEMETRY_TOPIC
    valueFrom:
      configMapKeyRef:
        key: reeferTelemetryTopic
        name: kafka-topics
  - name: CONTAINER_TOPIC
    valueFrom:
      configMapKeyRef:
        key: containersTopic
        name: kafka-topics
  - name: KAFKA_APIKEY
    valueFrom:
      secretKeyRef:
        key: binding
        name: eventstreams-apikey
  - name: KAFKA_CERT
    value: /certs/es-cert.pem
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: reefer-simulator
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
  volumeMounts:
  - mountPath: /certs
    name: eventstreams-cert-pem
  volumes:
  - name: eventstreams-cert-pem
    secret:
      optional: true
      secretName: eventstreams-cert-pem
status: {}
