apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/committer: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/contextDir: /simulator
    commit.image.appsody.dev/date: Tue May 12 09:41:39 2020 -0700
    commit.image.appsody.dev/message: typo in main index
    image.opencontainers.org/created: "2020-05-29T13:14:42+02:00"
    image.opencontainers.org/documentation: https://github.com/jesusmah/refarch-reefer-ml
    image.opencontainers.org/revision: eec58f83ff69dd749b84c7ed04403bb19bbf1c25-modified
    image.opencontainers.org/source: https://github.com/jesusmah/refarch-reefer-ml/tree/master
    image.opencontainers.org/url: https://github.com/jesusmah/refarch-reefer-ml
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.1
    stack.appsody.dev/created: 2019-11-14T10:29:19+0000
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: appsody/python-flask:0.1.6
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: reefer-simulator
    stack.appsody.dev/version: 0.1.6
  name: reefer-simulator
spec:
  applicationImage: ibmcase/kcontainer-reefer-ml-flask-simulator:test
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: TELEMETRY_TOPIC
    valueFrom:
      configMapKeyRef:
        key: reeferTelemetryTopic
        name: kafka-topics
  - name: CONTAINER_TOPIC
    valueFrom:
      configMapKeyRef:
        key: containersTopic
        name: kafka-topics
  - name: KAFKA_APIKEY
    valueFrom:
      secretKeyRef:
        key: binding
        name: eventstreams-apikey
  - name: KAFKA_CERT
    value: /certs/es-cert.pem
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: reefer-simulator
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
  volumeMounts:
  - mountPath: /certs
    name: eventstreams-cert-pem
  volumes:
  - name: eventstreams-cert-pem
    secret:
      optional: true
      secretName: eventstreams-cert-pem
status: {}
